name: autopilot-qt
version: 1.4
summary: Autopilot QT
grade: stable
description: |
  This project makes Qt applications introspectable by autopilot when started with the -testability flag.
  This allows autopilot to test any existing Qt application, without having to rebuild the application
  under test.

confinement: strict

slots:
  testability:
    content: testability
    interface: content
    read:
      - usr/lib

parts:
  autopilot-qt5:
    plugin: qmake
    qt-version: qt5
    source: .
    build-packages: ['g++', 'debhelper', 'libgl1-mesa-dev', 'libgles2-mesa-dev', 'libqt4-dev', 'libxpathselect-dev', 'mesa-common-dev', 'pkg-config', 'qt4-qmake', 'qt5-qmake', 'qtbase5-dev', 'qtchooser', 'qtdeclarative5-dev', 'xvfb']
    stage-packages:
      - libxpathselect1.4v5
    filesets:
       libs:
        - usr/lib/*/libxpathselect*
        - usr/lib/libautopilot_driver_qt5.so*
        - usr/lib/libqttestability*
    stage:
      - $libs
    snap:
      - $libs

  autopilot-qt4:
    plugin: qmake
    qt-version: qt4
    source: .
    build-packages:
      - libxpathselect-dev
    filesets:
       libs:
        - usr/lib/libautopilot_driver_qt4.so*
    stage:
      - $libs
    snap:
      - $libs
